/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.proyectofinal.main;

import com.proyectofinal.datos.DAOMaestros;
import com.proyectofinal.entidades.Maestro;
import javax.swing.JOptionPane;

/**
 *
 * @author al_12
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        fondo = new javax.swing.JLabel();
        etiquetaNombreUsuario = new javax.swing.JLabel();
        etiquetaContraseña = new javax.swing.JLabel();
        campoNombreUsuario = new javax.swing.JTextField();
        campoContraseña = new javax.swing.JPasswordField();
        etiquetaCopyright = new javax.swing.JLabel();
        etiquetaTitulo = new javax.swing.JLabel();
        botonInicioSesion = new javax.swing.JButton();
        botonCrearUsuario = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo.PNG"))); // NOI18N
        fondo.setText("jLabel1");
        jLayeredPane1.add(fondo);
        fondo.setBounds(0, 0, 760, 430);

        etiquetaNombreUsuario.setBackground(new java.awt.Color(255, 255, 255));
        etiquetaNombreUsuario.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        etiquetaNombreUsuario.setText("Usuario");
        jLayeredPane1.setLayer(etiquetaNombreUsuario, javax.swing.JLayeredPane.PALETTE_LAYER);
        jLayeredPane1.add(etiquetaNombreUsuario);
        etiquetaNombreUsuario.setBounds(90, 100, 110, 40);

        etiquetaContraseña.setBackground(new java.awt.Color(255, 255, 255));
        etiquetaContraseña.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        etiquetaContraseña.setText("Contraseña");
        jLayeredPane1.setLayer(etiquetaContraseña, javax.swing.JLayeredPane.PALETTE_LAYER);
        jLayeredPane1.add(etiquetaContraseña);
        etiquetaContraseña.setBounds(90, 180, 180, 60);

        campoNombreUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNombreUsuarioActionPerformed(evt);
            }
        });
        jLayeredPane1.setLayer(campoNombreUsuario, javax.swing.JLayeredPane.PALETTE_LAYER);
        jLayeredPane1.add(campoNombreUsuario);
        campoNombreUsuario.setBounds(90, 140, 300, 40);

        campoContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoContraseñaActionPerformed(evt);
            }
        });
        jLayeredPane1.setLayer(campoContraseña, javax.swing.JLayeredPane.PALETTE_LAYER);
        jLayeredPane1.add(campoContraseña);
        campoContraseña.setBounds(90, 230, 300, 40);

        etiquetaCopyright.setText("© 2025 Educa+. Versión 0.1 (Beta). Todos los derechos reservados.");
        jLayeredPane1.setLayer(etiquetaCopyright, javax.swing.JLayeredPane.PALETTE_LAYER);
        jLayeredPane1.add(etiquetaCopyright);
        etiquetaCopyright.setBounds(20, 400, 410, 17);

        etiquetaTitulo.setFont(new java.awt.Font("Segoe UI Black", 1, 72)); // NOI18N
        etiquetaTitulo.setText("Educa+");
        jLayeredPane1.setLayer(etiquetaTitulo, javax.swing.JLayeredPane.PALETTE_LAYER);
        jLayeredPane1.add(etiquetaTitulo);
        etiquetaTitulo.setBounds(90, 0, 390, 100);

        botonInicioSesion.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        botonInicioSesion.setText("Iniciar sesión");
        botonInicioSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonInicioSesionActionPerformed(evt);
            }
        });
        jLayeredPane1.setLayer(botonInicioSesion, javax.swing.JLayeredPane.PALETTE_LAYER);
        jLayeredPane1.add(botonInicioSesion);
        botonInicioSesion.setBounds(90, 290, 160, 32);

        botonCrearUsuario.setForeground(new java.awt.Color(51, 102, 255));
        botonCrearUsuario.setText("¿No tienes cuenta?  Regístrate");
        botonCrearUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCrearUsuarioActionPerformed(evt);
            }
        });
        jLayeredPane1.setLayer(botonCrearUsuario, javax.swing.JLayeredPane.PALETTE_LAYER);
        jLayeredPane1.add(botonCrearUsuario);
        botonCrearUsuario.setBounds(90, 340, 290, 23);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 752, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 426, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoNombreUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNombreUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNombreUsuarioActionPerformed

    private void campoContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoContraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoContraseñaActionPerformed

    private void botonInicioSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonInicioSesionActionPerformed
        String login = campoNombreUsuario.getText().trim();
        String password = campoContraseña.getText().trim();
        if (login.isEmpty() || password.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Debe especificar usuario y contraseña", "Aviso",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }
        DAOMaestros du = new DAOMaestros();
        Maestro maestro = du.getUsuario(login);
        if (maestro == null || !password.equals(maestro.getPassword())) {
            JOptionPane.showMessageDialog(this, "Usuario o contraseña incorrectos",
                    "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            VentanaPrincipal principal = new VentanaPrincipal(maestro);
            dispose();
            principal.setVisible(true);
        }
    }//GEN-LAST:event_botonInicioSesionActionPerformed

    private void botonCrearUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCrearUsuarioActionPerformed
        new PantallaRegistro(this, true).setVisible(true);
    }//GEN-LAST:event_botonCrearUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCrearUsuario;
    private javax.swing.JButton botonInicioSesion;
    private javax.swing.JPasswordField campoContraseña;
    private javax.swing.JTextField campoNombreUsuario;
    private javax.swing.JLabel etiquetaContraseña;
    private javax.swing.JLabel etiquetaCopyright;
    private javax.swing.JLabel etiquetaNombreUsuario;
    private javax.swing.JLabel etiquetaTitulo;
    private javax.swing.JLabel fondo;
    private javax.swing.JLayeredPane jLayeredPane1;
    // End of variables declaration//GEN-END:variables
}
