/*
 * Esta clase representa la ventana donde se realizan operaciones con Asignaturas.
 * Dependiendo del valor del enum, se hará una operación u otra.
 */
package com.proyectofinal.main;

import com.proyectofinal.datos.DAOAsignaturas;
import com.proyectofinal.entidades.Asignatura;
import com.proyectofinal.entidades.Maestro;
import com.proyectofinal.main.VentanaPrincipal.Modo;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author al_12
 */
public class ModificarAsignatura extends javax.swing.JDialog {

    private Maestro maestro;
    private Asignatura asignatura;
    private Modo modo;


    /**
     * Creates new form AñadirAsignatura
     */
    public ModificarAsignatura(java.awt.Frame parent, boolean modal, Maestro maestro, Modo modo) {
        super(parent, modal);
        this.maestro = maestro;
        this.modo = modo;
        initComponents();
        etiquetaAsignatura.setText(modo.toString().substring(0, 1).toUpperCase()
                + modo.toString().substring(1).toLowerCase()
                + " asignatura");
        if (modo == Modo.AÑADIR) {
            botonAceptar.setText("Añadir");
        }
    }

    public ModificarAsignatura(java.awt.Frame parent, boolean modal, Maestro maestro, Asignatura asignatura, Modo modo) {
        super(parent, modal);
        this.maestro = maestro;
        this.asignatura = asignatura;
        this.modo = modo;
        initComponents();
        etiquetaAsignatura.setText(modo.toString().substring(0, 1).toUpperCase()
                + modo.toString().substring(1).toLowerCase()
                + " asignatura");
        if (modo == Modo.EDITAR) {
            botonAceptar.setText("Editar");
            nombreAsignatura.setText("Nuevo nombre");
        } else if (modo == Modo.ELIMINAR) {
            botonAceptar.setText("Eliminar");
            nombreAsignatura.setText("¿Quieres eliminar?");
            campoNombreAsignatura.setText(asignatura.getNombre());
            campoNombreAsignatura.setEnabled(false);
        }
    }

    private void añadirAsignatura() {
        if (campoNombreAsignatura.getText().isBlank() || campoNombreAsignatura.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe introducir un nombre",
                    "Error", JOptionPane.WARNING_MESSAGE);
        } else if (maestro.getAsignaturas().stream().anyMatch((a) -> a.getNombre().trim().equalsIgnoreCase(campoNombreAsignatura.getText().trim()))) {
            JOptionPane.showMessageDialog(this, "El nombre de la asignatura ya existe",
                    "Error", JOptionPane.WARNING_MESSAGE);
        } else {
            DAOAsignaturas da = new DAOAsignaturas();
            da.añadirAsignatura(campoNombreAsignatura.getText(), maestro);
            this.dispose();
        }
    }

    private void editarAsignatura() {
        if (campoNombreAsignatura.getText().isBlank() || campoNombreAsignatura.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe introducir un nombre",
                    "Error", JOptionPane.WARNING_MESSAGE);
        } else if (maestro.getAsignaturas().stream().anyMatch((a) -> a.getNombre().trim().equalsIgnoreCase(campoNombreAsignatura.getText().trim()))) {
            JOptionPane.showMessageDialog(this, "El nombre de la asignatura ya existe",
                    "Error", JOptionPane.WARNING_MESSAGE);
        } else {
            DAOAsignaturas da = new DAOAsignaturas();
            da.editarAsignatura(campoNombreAsignatura.getText(), asignatura.getId());
            asignatura.setNombre(campoNombreAsignatura.getText().trim());
            this.dispose();
        }
    }
    
        private void eliminarAsignatura() {
            DAOAsignaturas da = new DAOAsignaturas();
            da.eliminarAsignatura(asignatura);
            maestro.getAsignaturas().remove(asignatura);
            this.dispose();
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        nombreAsignatura = new javax.swing.JLabel();
        botonAceptar = new javax.swing.JButton();
        campoNombreAsignatura = new javax.swing.JTextField();
        etiquetaAsignatura = new javax.swing.JLabel();
        botonCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(193, 239, 255));

        nombreAsignatura.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        nombreAsignatura.setText("Nombre");

        botonAceptar.setText("Aceptar");
        botonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarActionPerformed(evt);
            }
        });

        campoNombreAsignatura.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        campoNombreAsignatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNombreAsignaturaActionPerformed(evt);
            }
        });
        campoNombreAsignatura.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                campoNombreAsignaturaKeyPressed(evt);
            }
        });

        etiquetaAsignatura.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        etiquetaAsignatura.setText(" ");

        botonCancelar.setText("Cancelar");
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(nombreAsignatura, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(campoNombreAsignatura, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(etiquetaAsignatura, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(botonAceptar)
                .addGap(70, 70, 70)
                .addComponent(botonCancelar)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(etiquetaAsignatura)
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreAsignatura)
                    .addComponent(campoNombreAsignatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonAceptar)
                    .addComponent(botonCancelar))
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarActionPerformed

        if (modo == Modo.AÑADIR) {
            añadirAsignatura();
        } else if (modo == Modo.EDITAR) {
            editarAsignatura();
        }else if(modo==Modo.ELIMINAR){
            eliminarAsignatura();
        }
    }//GEN-LAST:event_botonAceptarActionPerformed

    private void campoNombreAsignaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNombreAsignaturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNombreAsignaturaActionPerformed

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_botonCancelarActionPerformed

    private void campoNombreAsignaturaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoNombreAsignaturaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            botonAceptarActionPerformed(null);
        }

    }//GEN-LAST:event_campoNombreAsignaturaKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificarAsignatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificarAsignatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificarAsignatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificarAsignatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                ModificarAsignatura dialog = new ModificarAsignatura(new javax.swing.JFrame(), true, null, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAceptar;
    private javax.swing.JButton botonCancelar;
    private javax.swing.JTextField campoNombreAsignatura;
    private javax.swing.JLabel etiquetaAsignatura;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nombreAsignatura;
    // End of variables declaration//GEN-END:variables
}
