/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.proyectofinal.main;

import com.proyectofinal.entidades.Maestro;
import javax.swing.JFrame;

/**
 *
 * @author al_12
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal(Maestro maestro) {
        initComponents();
        etiquetaBienvenida.setText("Bienvenid@, nombreMaestro");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        fondo = new javax.swing.JLabel();
        etiquetaBienvenida = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablaAsignaturas = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        tablaTemas = new javax.swing.JTable();
        jScrollPane6 = new javax.swing.JScrollPane();
        tablaActividades = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondoPrincipal.jpg"))); // NOI18N
        jLayeredPane1.add(fondo);
        fondo.setBounds(-10, -160, 1570, 1050);

        etiquetaBienvenida.setFont(new java.awt.Font("Segoe UI Black", 3, 36)); // NOI18N
        etiquetaBienvenida.setForeground(new java.awt.Color(51, 51, 255));
        etiquetaBienvenida.setText("Bienvenid@, ");
        jLayeredPane1.setLayer(etiquetaBienvenida, javax.swing.JLayeredPane.PALETTE_LAYER);
        jLayeredPane1.add(etiquetaBienvenida);
        etiquetaBienvenida.setBounds(90, 30, 520, 80);

        tablaAsignaturas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Asignaturas"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaAsignaturas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaAsignaturasMouseClicked(evt);
            }
        });
        tablaAsignaturas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tablaAsignaturasKeyReleased(evt);
            }
        });
        jScrollPane4.setViewportView(tablaAsignaturas);
        if (tablaAsignaturas.getColumnModel().getColumnCount() > 0) {
            tablaAsignaturas.getColumnModel().getColumn(0).setResizable(false);
        }

        jLayeredPane1.setLayer(jScrollPane4, javax.swing.JLayeredPane.PALETTE_LAYER);
        jLayeredPane1.add(jScrollPane4);
        jScrollPane4.setBounds(80, 230, 400, 480);

        tablaTemas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Temas"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(tablaTemas);
        if (tablaTemas.getColumnModel().getColumnCount() > 0) {
            tablaTemas.getColumnModel().getColumn(0).setResizable(false);
        }

        jLayeredPane1.setLayer(jScrollPane5, javax.swing.JLayeredPane.PALETTE_LAYER);
        jLayeredPane1.add(jScrollPane5);
        jScrollPane5.setBounds(560, 230, 400, 480);

        tablaActividades.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Asignaturas"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane6.setViewportView(tablaActividades);
        if (tablaActividades.getColumnModel().getColumnCount() > 0) {
            tablaActividades.getColumnModel().getColumn(0).setResizable(false);
        }

        jLayeredPane1.setLayer(jScrollPane6, javax.swing.JLayeredPane.PALETTE_LAYER);
        jLayeredPane1.add(jScrollPane6);
        jScrollPane6.setBounds(1050, 230, 400, 480);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1552, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 885, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tablaAsignaturasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaAsignaturasMouseClicked
        int indice = tablaAsignaturas.getSelectedRow();
        if(indice !=-1){
            
        }
    }//GEN-LAST:event_tablaAsignaturasMouseClicked

    private void tablaAsignaturasKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tablaAsignaturasKeyReleased
        tablaAsignaturasMouseClicked(null);
    }//GEN-LAST:event_tablaAsignaturasKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel etiquetaBienvenida;
    private javax.swing.JLabel fondo;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTable tablaActividades;
    private javax.swing.JTable tablaAsignaturas;
    private javax.swing.JTable tablaTemas;
    // End of variables declaration//GEN-END:variables
}
