/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.proyectofinal.main;

import com.proyectofinal.entidades.Asignatura;
import com.proyectofinal.entidades.Maestro;
import com.proyectofinal.entidades.Tema;
import java.util.Collections;
import java.util.stream.Collectors;
import javax.swing.DefaultListModel;

/**
 *
 * @author al_12
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    Maestro m;
    private DefaultListModel<Asignatura> modeloListaAsignaturas = new DefaultListModel<>();
    private DefaultListModel<Tema> modeloListaTemas = new DefaultListModel<>();

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal(Maestro m) {
        this.m = m;
        initComponents();
        listaAsignaturas.setModel(modeloListaAsignaturas);
        listaTemas.setModel(modeloListaTemas);
        for (Asignatura a : m.getAsignaturas()) {
            modeloListaAsignaturas.addElement(a);
        }

        editarAsignatura.setEnabled(false);
        eliminarAsignatura.setEnabled(false);
        añadirTema.setEnabled(false);
        editarTema.setEnabled(false);
        eliminarTema.setEnabled(false);
        añadirActividad.setEnabled(false);
        editarActividad.setEnabled(false);
        eliminarActividad.setEnabled(false);
        etiquetaBienvenida.setText("Usuario " + m.getLogin());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pestañas = new javax.swing.JTabbedPane();
        pestañaPrincipal = new javax.swing.JPanel();
        añadirAsignatura = new javax.swing.JButton();
        editarAsignatura = new javax.swing.JButton();
        añadirTema = new javax.swing.JButton();
        editarTema = new javax.swing.JButton();
        añadirActividad = new javax.swing.JButton();
        editarActividad = new javax.swing.JButton();
        eliminarAsignatura = new javax.swing.JButton();
        eliminarTema = new javax.swing.JButton();
        eliminarActividad = new javax.swing.JButton();
        etiquetaBienvenida = new javax.swing.JLabel();
        etiquetaCopyright = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        listaAsignaturas = new javax.swing.JList<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaTemas = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaActividades = new javax.swing.JList<>();
        pestañaCalendario = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pestañaPrincipal.setBackground(new java.awt.Color(193, 239, 255));

        añadirAsignatura.setText("Añadir asignatura");
        añadirAsignatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                añadirAsignaturaActionPerformed(evt);
            }
        });

        editarAsignatura.setText("Editar asignatura");
        editarAsignatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarAsignaturaActionPerformed(evt);
            }
        });

        añadirTema.setText("Añadir tema");
        añadirTema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                añadirTemaActionPerformed(evt);
            }
        });

        editarTema.setText("Editar tema");
        editarTema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarTemaActionPerformed(evt);
            }
        });

        añadirActividad.setText("Añadir Actividad");
        añadirActividad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                añadirActividadActionPerformed(evt);
            }
        });

        editarActividad.setText("Editar actividad");
        editarActividad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarActividadActionPerformed(evt);
            }
        });

        eliminarAsignatura.setText("Eliminar asignatura");
        eliminarAsignatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarAsignaturaActionPerformed(evt);
            }
        });

        eliminarTema.setText("Eliminar tema");
        eliminarTema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarTemaActionPerformed(evt);
            }
        });

        eliminarActividad.setText("Eliminar actividad");
        eliminarActividad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActividadActionPerformed(evt);
            }
        });

        etiquetaBienvenida.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N

        etiquetaCopyright.setText("© 2025 Educa+. Versión 0.1 (Beta). Todos los derechos reservados.");

        listaAsignaturas.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listaAsignaturas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaAsignaturasMouseClicked(evt);
            }
        });
        listaAsignaturas.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listaAsignaturasValueChanged(evt);
            }
        });
        jScrollPane4.setViewportView(listaAsignaturas);

        listaTemas.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(listaTemas);

        listaActividades.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listaActividades.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(listaActividades);

        javax.swing.GroupLayout pestañaPrincipalLayout = new javax.swing.GroupLayout(pestañaPrincipal);
        pestañaPrincipal.setLayout(pestañaPrincipalLayout);
        pestañaPrincipalLayout.setHorizontalGroup(
            pestañaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pestañaPrincipalLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(pestañaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pestañaPrincipalLayout.createSequentialGroup()
                        .addComponent(etiquetaCopyright, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(50, 50, 50))
                    .addGroup(pestañaPrincipalLayout.createSequentialGroup()
                        .addGroup(pestañaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pestañaPrincipalLayout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(añadirAsignatura, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(editarAsignatura, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(eliminarAsignatura, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pestañaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pestañaPrincipalLayout.createSequentialGroup()
                                .addGap(158, 158, 158)
                                .addGroup(pestañaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(editarTema, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(eliminarTema, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(133, 133, 133)
                                .addGroup(pestañaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(editarActividad, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(eliminarActividad, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(113, Short.MAX_VALUE))
                            .addGroup(pestañaPrincipalLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(pestañaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(añadirTema, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jScrollPane1))
                                .addGap(133, 133, 133)
                                .addGroup(pestañaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(añadirActividad, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                    .addComponent(jScrollPane2))
                                .addGap(113, 113, 113))))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pestañaPrincipalLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(etiquetaBienvenida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(73, 73, 73))
        );
        pestañaPrincipalLayout.setVerticalGroup(
            pestañaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pestañaPrincipalLayout.createSequentialGroup()
                .addComponent(etiquetaBienvenida, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                .addGap(40, 40, 40)
                .addGroup(pestañaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane4)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pestañaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(añadirTema, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(añadirAsignatura)
                    .addComponent(añadirActividad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10)
                .addGroup(pestañaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pestañaPrincipalLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(editarActividad))
                    .addGroup(pestañaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(editarAsignatura)
                        .addComponent(editarTema)))
                .addGap(8, 8, 8)
                .addGroup(pestañaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eliminarAsignatura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(eliminarActividad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(eliminarTema, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(etiquetaCopyright, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pestañas.addTab("Principal", pestañaPrincipal);

        pestañaCalendario.setBackground(new java.awt.Color(255, 225, 231));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        jLabel2.setText("Educa+");

        javax.swing.GroupLayout pestañaCalendarioLayout = new javax.swing.GroupLayout(pestañaCalendario);
        pestañaCalendario.setLayout(pestañaCalendarioLayout);
        pestañaCalendarioLayout.setHorizontalGroup(
            pestañaCalendarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pestañaCalendarioLayout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 806, Short.MAX_VALUE))
        );
        pestañaCalendarioLayout.setVerticalGroup(
            pestañaCalendarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pestañaCalendarioLayout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 459, Short.MAX_VALUE))
        );

        pestañas.addTab("Calendario", pestañaCalendario);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pestañas)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pestañas)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void eliminarActividadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActividadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eliminarActividadActionPerformed

    private void eliminarTemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarTemaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eliminarTemaActionPerformed

    private void eliminarAsignaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarAsignaturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eliminarAsignaturaActionPerformed

    private void editarActividadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarActividadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editarActividadActionPerformed

    private void añadirActividadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_añadirActividadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_añadirActividadActionPerformed

    private void editarTemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarTemaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editarTemaActionPerformed

    private void añadirTemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_añadirTemaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_añadirTemaActionPerformed

    private void editarAsignaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarAsignaturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editarAsignaturaActionPerformed

    private void añadirAsignaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_añadirAsignaturaActionPerformed
        new ModificarAsignatura(this, true, m, ModificarAsignatura.Modo.AÑADIR).setVisible(true);
        modeloListaAsignaturas.clear();
        modeloListaAsignaturas.addAll(m.getAsignaturas());

    }//GEN-LAST:event_añadirAsignaturaActionPerformed

    private void listaAsignaturasValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listaAsignaturasValueChanged
        /*editarAsignatura.setEnabled(true);
        modeloListaTemas.clear();
        modeloListaTemas.addAll(listaAsignaturas.getSelectedValue().getTemas());
        
        modeloListaTemas.addAll(m.getAsignaturas().stream()
                .filter(a -> a.getNombre().equalsIgnoreCase(listaAsignaturas.getSelectedValue()))
                .findFirst()
                .map(a -> a.getTemas().stream().map(Tema::getNombre).collect(Collectors.toList()))
                .orElse(Collections.emptyList()));
         */
    }//GEN-LAST:event_listaAsignaturasValueChanged

    private void listaAsignaturasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaAsignaturasMouseClicked
        editarAsignatura.setEnabled(true);
        eliminarAsignatura.setEnabled(true);
        modeloListaTemas.clear();
        modeloListaTemas.addAll(listaAsignaturas.getSelectedValue().getTemas());
    }//GEN-LAST:event_listaAsignaturasMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton añadirActividad;
    private javax.swing.JButton añadirAsignatura;
    private javax.swing.JButton añadirTema;
    private javax.swing.JButton editarActividad;
    private javax.swing.JButton editarAsignatura;
    private javax.swing.JButton editarTema;
    private javax.swing.JButton eliminarActividad;
    private javax.swing.JButton eliminarAsignatura;
    private javax.swing.JButton eliminarTema;
    private javax.swing.JLabel etiquetaBienvenida;
    private javax.swing.JLabel etiquetaCopyright;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JList<String> listaActividades;
    private javax.swing.JList<Asignatura> listaAsignaturas;
    private javax.swing.JList<Tema> listaTemas;
    private javax.swing.JPanel pestañaCalendario;
    private javax.swing.JPanel pestañaPrincipal;
    private javax.swing.JTabbedPane pestañas;
    // End of variables declaration//GEN-END:variables
}
